services:
  - docker
before_script:
  - docker pull curlimages/curl
script: docker run --rm curlimages/curl curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/37863/${PACKAGEHASH}/simulationcraft-cli/ &&
        docker run --rm curlimages/curl curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/37863/${PACKAGEHASH}/simulationcraft-gui/
